#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use verheesj\KillTheBeesGame\PlayCommand;

$application = new Application;
$application->add(new \verheesj\KillTheBeesGame\Commands\PlayCommand);
$application->setDefaultCommand('play', true);
$application->run();